//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZooShop.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Accounting
    {
        public int Id { get; set; }
        public int id_worker { get; set; }
        public int Id_Product { get; set; }
        public System.DateTime date { get; set; }
        public long Amount { get; set; }
        public long Total_price { get; set; }
    
        public virtual Product Product { get; set; }
        public virtual Worker Worker { get; set; }
    }
}
